version: '3'
services:
  lab6-tkvc-back:
    image: back-tkvs-lab5
    ports:
      - 5500:5500
    networks:
      - lab6-tkvc-network

  lab6-tkvc-front:
    image: front-tkvs-lab5
    ports:
      - 80:80
    networks:
      - lab6-tkvc-network

networks:
  lab6-tkvc-network:
    driver: bridge